# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [1]:
import pandas as pd
import numpy as np

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [2]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data)
df

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [3]:
df.Age

0    16
1    28
2    22
Name: Age, dtype: int64

In [4]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [23]:
df["Salary"] = [50000, 60000, 45000]
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

In [24]:
salary = pd.Series([50000, 60000, 45000], name="Salary")
df["Salary"] = salary
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [7]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [11]:
df["Birth year"] = 2025 - df["Age"]
df

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2009
1  Emily   28  Los Angeles   60000        1997
2   Ryan   22      Chicago   45000        2003

### Task 4.2

Add new calculated field `Average age`.

In [13]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [14]:
df["Age"] - df["Average age"]

0   -6.0
1    6.0
2    0.0
dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [19]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df1

    Name  Age
0   John   25
1  Emily   28
2   Ryan   22

In [18]:
df2

    Name         City
0  Emily  Los Angeles
1   Ryan      Chicago
2   Mike      Houston

In [33]:
merged_df1 = pd.merge(df1, df2, on="Name", how="inner")
merged_df1

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [34]:
merged_df2 = pd.merge(df1, df2, on="Name", how="outer")
merged_df2

    Name   Age         City
0  Emily  28.0  Los Angeles
1   John  25.0          NaN
2   Mike   NaN      Houston
3   Ryan  22.0      Chicago

In [37]:
concat_df1 = pd.concat([df1, df2], axis=0)
concat_df1

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

In [38]:
concat_df2 = pd.concat([df1, df2], axis=1)
concat_df2

    Name  Age   Name         City
0   John   25  Emily  Los Angeles
1  Emily   28   Ryan      Chicago
2   Ryan   22   Mike      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [43]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [53]:
s2 + s1

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [54]:
s2 - s1

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [55]:
s2 * s1

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [56]:
s2 / s1

0    6.000000
1    3.500000
2    2.666667
3    2.250000
4    2.000000
dtype: float64

In [57]:
s2 ** s1

0         6
1        49
2       512
3      6561
4    100000
dtype: int64

In [58]:
s2 // s1

0    6
1    3
2    2
3    2
4    2
dtype: int64

In [59]:
s2 % s1

0    0
1    1
2    2
3    1
4    0
dtype: int64

In [61]:
s1[s1 % 2 == 0]

1    2
3    4
dtype: int64

In [64]:
s2[s2 % 2 != 0]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [66]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [68]:
s_upper = s.str.upper()
s_upper

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [69]:
s_length = s.str.len()
s_length

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [70]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 4.31 s
Wall time: 4.39 s

[42.2, 54.0, 46.4, 57.8, 48.2, 51.6, 39.8, 37.4, 33.2, 37.2]

### Solution using Pandas and Numpy

In [74]:
%%time
s = pd.Series([random.randint(1, 100) for _ in range(10000000)])
result = s.rolling(window=5).mean().dropna().tolist()
print(result[:10])

[25.8, 44.8, 37.8, 36.4, 38.2, 42.4, 31.4, 49.4, 54.8, 59.6]
CPU times: total: 4.61 s
Wall time: 4.71 s